### ISSUE TITLE
Do you want to try to port vs impostor v4 with me?

### ISSUE THREAD

**Issue by fnfgo** [fnfporterhi/an-update#1]
Really alot of kids at school need and whant this but levis ignoring me, i dont want to disturb memehovy and dom blocked me for some reason. Also im sorry im bothering you you already have enough to deal with

**Comment by fnfporterhi** [comment]
i’m sorry, but i really don’t know you?

**Comment by fnfporterhi** [comment]
but yeah sure, when i get a chance to get to my grandparents and have a pc

**Comment by fnfporterhi** [comment]
also if you want them, i have a BUNCH of ports on my bookmarks folder.

**Comment by fnfgo** [comment]
okay thanks for answering :)

**Comment by fnfporterhi** [comment]
you’re welcome
